services:
  # Prism Server
  prism-server:
    image: prism-server:latest
    container_name: prism-server
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - PRISM_SERVER_HOST=0.0.0.0
      - PRISM_SERVER_TCP_PORT=8080
      - PRISM_SERVER_API_PORT=8081
      - PRISM_LOGGING_LEVEL=INFO
      - PRISM_DATABASE_PATH=/data/prism.db
    volumes:
      - ./data:/data
      - ./config:/app/config
    ports:
      - "8080:8080"  # TCP server for client connections
      - "8081:8081"  # REST API for health checks
    networks:
      - prism-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Web Server
  nginx:
    image: prism-web:latest
    container_name: prism-nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      - prism-server
    environment:
      - API_URL=http://prism-server:8081
    networks:
      - prism-network

  # PowerDNS Database (PostgreSQL)
  powerdns-database:
    image: postgres:15-alpine
    container_name: powerdns-database
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${PDNS_DB_NAME:-powerdns}
      POSTGRES_USER: ${PDNS_DB_USER:-powerdns}
      POSTGRES_PASSWORD: ${PDNS_DB_PASSWORD}
    volumes:
      - powerdns-db-data:/var/lib/postgresql/data
      - ./powerdns/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    networks:
      - prism-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PDNS_DB_USER:-powerdns}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PowerDNS Server
  powerdns-server:
    build:
      context: ./powerdns
      dockerfile: Dockerfile
    image: powerdns:local
    container_name: powerdns-server
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:8053"
    environment:
      PDNS_API_KEY: ${PDNS_API_KEY}
      PDNS_DB_HOST: powerdns-database
      PDNS_DB_PORT: 5432
      PDNS_DB_NAME: ${PDNS_DB_NAME:-powerdns}
      PDNS_DB_USER: ${PDNS_DB_USER:-powerdns}
      PDNS_DB_PASSWORD: ${PDNS_DB_PASSWORD}
      PDNS_API_ALLOW_FROM: ${PDNS_API_ALLOW_FROM:-0.0.0.0/0,::/0}
      PDNS_DEFAULT_ZONE: ${PDNS_DEFAULT_ZONE:-managed.prism.local}
      # Performance tuning for production
      PDNS_RECEIVER_THREADS: ${PDNS_RECEIVER_THREADS:-4}
      PDNS_DISTRIBUTOR_THREADS: ${PDNS_DISTRIBUTOR_THREADS:-4}
      PDNS_CACHE_TTL: ${PDNS_CACHE_TTL:-60}
      # Security settings
      PDNS_DISABLE_AXFR: ${PDNS_DISABLE_AXFR:-yes}
      PDNS_LOG_LEVEL: ${PDNS_LOG_LEVEL:-4}
    depends_on:
      powerdns-database:
        condition: service_healthy
    networks:
      - prism-network
    healthcheck:
      test: ["CMD", "pdns_control", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  powerdns-db-data:
    driver: local

networks:
  # Single unified network for all services
  prism-network:
    driver: bridge
    name: prism-network