# AlertManager configuration for Prism DNS

global:
  resolve_timeout: 5m

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: critical
      group_wait: 10s
      repeat_interval: 1h
    
    # Warning alerts - 15 minute delay
    - match:
        severity: warning
      receiver: warning
      group_wait: 15m
      repeat_interval: 4h
    
    # Info alerts - 1 hour delay
    - match:
        severity: info
      receiver: info
      group_wait: 1h
      repeat_interval: 24h

# Receivers
receivers:
  - name: 'default'
    # Configure your notification channels here
    # Example: webhook, email, slack, etc.
    
  - name: 'critical'
    # Critical alert notifications
    # webhook_configs:
    #   - url: 'http://your-webhook-endpoint/critical'
    
  - name: 'warning'
    # Warning alert notifications
    # webhook_configs:
    #   - url: 'http://your-webhook-endpoint/warning'
    
  - name: 'info'
    # Info alert notifications
    # webhook_configs:
    #   - url: 'http://your-webhook-endpoint/info'

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']