# Prism DNS Server Configuration (SCRUM-12)

# Server settings
server:
  tcp_port: 8080
  api_port: 8081
  host: "0.0.0.0"
  max_connections: 1000
  
# Database settings
database:
  path: "/app/data/prism.db"
  connection_pool_size: 20
  
# Heartbeat monitoring settings
heartbeat:
  check_interval: 30  # seconds
  timeout_multiplier: 2
  grace_period: 30  # seconds
  cleanup_after_days: 30
  
# Logging settings
logging:
  level: INFO
  file: "/app/data/server.log"
  max_size: 104857600  # 100MB
  backup_count: 5

# PowerDNS integration settings
powerdns:
  enabled: true
  api_url: "http://powerdns:8053/api/v1"
  api_key: "${PRISM_POWERDNS_API_KEY:-test-api-key-change-in-production}"
  default_zone: "managed.prism.local."
  default_ttl: 300
  timeout: 5
  retry_attempts: 3
  retry_delay: 1
  record_types:
    - A
    - AAAA
  auto_ptr: false