# Example Prism DNS Server Configuration (SCRUM-18)
# Copy this file to server.yaml and modify as needed

# Server connection settings
server:
  tcp_port: 8080              # Port for TCP client connections
  api_port: 8081              # Port for REST API
  host: "0.0.0.0"             # Interface to bind to (0.0.0.0 for all)
  max_connections: 1000       # Maximum concurrent connections
  
# Database settings
database:
  path: "./hosts.db"          # SQLite database file path
  connection_pool_size: 20    # Connection pool size
  
# Heartbeat monitoring settings
heartbeat:
  check_interval: 30          # How often to check for offline hosts (seconds)
  timeout_multiplier: 2       # Multiplier for client heartbeat interval
  grace_period: 30            # Additional grace period before marking offline (seconds)
  cleanup_after_days: 30      # Remove offline hosts after this many days
  
# Logging settings
logging:
  level: "INFO"               # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "./server.log"        # Log file path
  max_size: 104857600         # Maximum log file size (100MB)
  backup_count: 5             # Number of backup log files to keep

# API settings
api:
  enable_cors: true           # Enable Cross-Origin Resource Sharing
  cors_origins:               # Allowed CORS origins
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
  request_timeout: 30         # API request timeout in seconds

# PowerDNS integration settings
powerdns:
  enabled: false              # Set to true to enable PowerDNS integration
  api_url: "http://powerdns:8053/api/v1"  # PowerDNS API endpoint
  api_key: ""                 # API key for PowerDNS authentication
  default_zone: "managed.prism.local."     # Default DNS zone for records
  default_ttl: 300            # Default TTL for DNS records (seconds)
  timeout: 5                  # API request timeout in seconds
  retry_attempts: 3           # Number of retry attempts for failed requests
  retry_delay: 1              # Delay between retries in seconds
  record_types:               # Supported record types
    - A
    - AAAA
  auto_ptr: false             # Automatically create PTR records

# Environment Variable Overrides:
# PRISM_SERVER_TCP_PORT        - Override TCP server port
# PRISM_SERVER_API_PORT        - Override API server port
# PRISM_SERVER_HOST            - Override server host
# PRISM_DATABASE_PATH          - Override database file path
# PRISM_LOGGING_LEVEL          - Override logging level
# PRISM_LOGGING_FILE           - Override log file path
# PRISM_POWERDNS_ENABLED       - Enable/disable PowerDNS integration
# PRISM_POWERDNS_API_URL       - Override PowerDNS API URL
# PRISM_POWERDNS_API_KEY       - Set PowerDNS API key
# PRISM_POWERDNS_DEFAULT_ZONE  - Override default DNS zone
# PRISM_POWERDNS_DEFAULT_TTL   - Override default TTL