name: Test Any Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub Token
        run: |
          echo "Testing GITHUB_TOKEN (always available):"
          echo "Length: $(echo -n "${{ secrets.GITHUB_TOKEN }}" | wc -c)"
          
      - name: Test Custom Secrets
        env:
          MY_SECRET: ${{ secrets.EC2_SSH_KEY }}
          TEST_VAR: ${{ secrets.TEST_SECRET }}
        run: |
          echo "Testing EC2_SSH_KEY via env:"
          echo "Length: $(echo -n "${MY_SECRET}" | wc -c)"
          
          echo ""
          echo "Testing EC2_SSH_KEY direct:"
          echo "Length: $(echo -n "${{ secrets.EC2_SSH_KEY }}" | wc -c)"
          
          echo ""
          echo "Testing TEST_SECRET via env:"
          echo "Length: $(echo -n "${TEST_VAR}" | wc -c)"
          
          echo ""
          echo "Testing TEST_SECRET direct:"
          echo "Length: $(echo -n "${{ secrets.TEST_SECRET }}" | wc -c)"
          
          echo ""
          echo "Context info:"
          echo "Repo: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"